# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cknife"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike De La Loza"]
  s.date = "2014-09-07"
  s.description = "Cali Army Knife, a collection of command line tools, especially for popular API services."
  s.email = "mikedll@mikedll.com"
  s.executables = ["cknifeaws", "cknifedub", "cknifemail", "cknifenowtimestamp", "cknifewcdir", "cknifezerigo"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/cknifeaws",
    "bin/cknifedub",
    "bin/cknifemail",
    "bin/cknifenowtimestamp",
    "bin/cknifewcdir",
    "bin/cknifezerigo",
    "cknife.gemspec",
    "cknife.yml.sample",
    "lib/cknife/config.rb"
  ]
  s.homepage = "http://github.com/mikedll/cali-army-knife"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.28"
  s.summary = "Cali Army Knife"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 1.6"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.6"])
      s.add_runtime_dependency(%q<i18n>, ["~> 0.6.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0"])
      s.add_runtime_dependency(%q<actionmailer>, [">= 3.0"])
      s.add_runtime_dependency(%q<thor>, [">= 0.14"])
      s.add_runtime_dependency(%q<builder>, [">= 3.0"])
      s.add_runtime_dependency(%q<fog>, [">= 1.15"])
      s.add_runtime_dependency(%q<unf>, [">= 0.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0"])
    else
      s.add_dependency(%q<rest-client>, [">= 1.6"])
      s.add_dependency(%q<nokogiri>, [">= 1.6"])
      s.add_dependency(%q<i18n>, ["~> 0.6.0"])
      s.add_dependency(%q<activesupport>, [">= 3.0"])
      s.add_dependency(%q<actionmailer>, [">= 3.0"])
      s.add_dependency(%q<thor>, [">= 0.14"])
      s.add_dependency(%q<builder>, [">= 3.0"])
      s.add_dependency(%q<fog>, [">= 1.15"])
      s.add_dependency(%q<unf>, [">= 0.1"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 1.6"])
    s.add_dependency(%q<nokogiri>, [">= 1.6"])
    s.add_dependency(%q<i18n>, ["~> 0.6.0"])
    s.add_dependency(%q<activesupport>, [">= 3.0"])
    s.add_dependency(%q<actionmailer>, [">= 3.0"])
    s.add_dependency(%q<thor>, [">= 0.14"])
    s.add_dependency(%q<builder>, [">= 3.0"])
    s.add_dependency(%q<fog>, [">= 1.15"])
    s.add_dependency(%q<unf>, [">= 0.1"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0"])
  end
end

