# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cknife 1.4.2 ruby lib

Gem::Specification.new do |s|
  s.name = "cknife".freeze
  s.version = "1.4.2".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Michael Rivera".freeze]
  s.date = "2024-04-10"
  s.description = "A collection of command line tools, especially for popular API services.".freeze
  s.email = "soymrmike@gmail.com".freeze
  s.executables = ["cknifeaws".freeze, "cknifedub".freeze, "cknifemail".freeze, "cknifemon".freeze, "cknifemysql".freeze, "cknifenowtimestamp".freeze, "cknifepg".freeze, "cknifewcdir".freeze]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/cknifeaws",
    "bin/cknifedub",
    "bin/cknifemail",
    "bin/cknifemon",
    "bin/cknifemysql",
    "bin/cknifenowtimestamp",
    "bin/cknifepg",
    "bin/cknifewcdir",
    "cknife.gemspec",
    "cknife.yml.sample",
    "doc/remote_ubuntu_machine.md",
    "lib/cknife/backgrounded_polling.rb",
    "lib/cknife/cknife_aws.rb",
    "lib/cknife/cknife_mon.rb",
    "lib/cknife/cknife_mysql.rb",
    "lib/cknife/cknife_pg.rb",
    "lib/cknife/command_line.rb",
    "lib/cknife/config.rb",
    "lib/cknife/monitor.rb",
    "lib/cknife/repetition.rb"
  ]
  s.homepage = "http://github.com/mikedll/cknife".freeze
  s.licenses = ["".freeze]
  s.rubygems_version = "3.5.3".freeze
  s.summary = "CKnife".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<rest-client>.freeze, [">= 1.8.0".freeze, "~> 1".freeze])
  s.add_runtime_dependency(%q<nokogiri>.freeze, [">= 1.10.4".freeze, "~> 1".freeze])
  s.add_runtime_dependency(%q<i18n>.freeze, [">= 0.6.6".freeze])
  s.add_runtime_dependency(%q<activesupport>.freeze, [">= 4.2.9".freeze])
  s.add_runtime_dependency(%q<actionpack>.freeze, [">= 4.2.9".freeze])
  s.add_runtime_dependency(%q<mail>.freeze, ["~> 2.5.5".freeze])
  s.add_runtime_dependency(%q<thor>.freeze, [">= 0.14".freeze, "~> 0".freeze])
  s.add_runtime_dependency(%q<builder>.freeze, ["~> 3.0".freeze])
  s.add_runtime_dependency(%q<fog-aws>.freeze, ["< 3.0".freeze])
  s.add_runtime_dependency(%q<unf>.freeze, [">= 0.1".freeze, "~> 0".freeze])
  s.add_runtime_dependency(%q<daemons>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<loofah>.freeze, ["~> 2.2.3".freeze])
  s.add_development_dependency(%q<bundler>.freeze, ["~> 2.0".freeze])
  s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.1".freeze])
end

